#!/bin/sh

if [ $# -ne 1 ] ; then
        echo 'Usage: zerm2pdf [year]'
        exit 1
fi

if [ ! -f "cfgs/$1.z2p" ] ; then
        echo 'Config file does not exist.'
        exit 2
fi

if [ ! -d ../zerm.eu ] ; then
        echo 'zerm.eu directory does not exist.'
        exit 3
fi

which sed cat pandoc >/dev/null || exit 4

ids="$(cat cfgs/$1.z2p)"

articles=""

for id in $ids ; do
        articles="$articles $(grep ",$id$" ../zerm.eu/articles.csv | cut -d, -f2)"
done

for a in $articles ; do
        sed 's/🥰/[...]/g' "../zerm.eu/zerm/$a.md" | \
        sed 's/Михаил Сергеевич Горбачёв/(Kyrillische Buchstaben werden in der Gesamtausgabe noch nicht unterstützt)/g' | \
        sed 's/≠/!=/g'
done | cat -s | pandoc -o "../zerm.eu/$1.pdf"
