#!/bin/bash

if [ $# -lt 2 ] ; then
        echo 'Usage: zerm2pdf [year] [zerm.eu-directory]'
        exit 1
fi

if [ ! -f "cfgs/$1.z2p" ] ; then
        echo 'Config file does not exist.'
        exit 2
fi

if [ ! -d "$2" ] ; then
        echo 'zerm.eu directory does not exist.'
        exit 3
fi

source "cfgs/$1.z2p"

articles=""

for id in $ids ; do
        articles="$articles $(sed "s/<html><head><meta http-equiv='refresh' content='0; URL=https:\\/\\/zerm\\.eu\\/zerm\\///" "$2/zm/$id.html" | sed "s/'><script>window\\.location\\.href = 'https:\\/\\/zerm\\.eu\\/zerm\\/.\\+\\.html'<\\/script><\\/head><body>Sie sollten <a href='https:\\/\\/zerm.eu\\/zerm\\/.\\+\\.html'>hierhin<\\/a> weitergeleitet werden.<\\/body><\\/html>//")"
done

articles="$(echo "$articles" | sed 's/^ //')"

#inkscape -z -e "/tmp/$1.png" "fpgs/$1.svg" > /dev/null
#echo "![the front page](/tmp/$1.png)" > /tmp/zerm2pdf.md

for a in $articles ; do
        sed 's/<\/\?html>//' "$2/zerm/$a" | \
                sed 's/<\/\?head>//' | \
                sed 's/<\/\?body>//' | \
                sed 's/^.*twitter.*tweet.*text.*zerm\.link.*$//' | \
                sed "s/<a href='\\.\\.\\/index\\.html'>zurück<\\/a>//" | \
                sed 's/<title>.*<\/title>//' | \
                sed 's/<link .*>//' | \
                sed "s/<meta charset='utf-8'\\/>//" | \
                sed 's/<\/\?footer>//g' | \
                sed 's/<br\/>/\n/g' | \
                sed 's/<\/\?p>/\n/g' | \
                perl -pe 's|<h1>(.*?)</h1>|# \1|g' | \
                perl -pe 's|<h2>(.*?)</h2>|## \1|g' | \
                perl -pe 's|<h3>(.*?)</h3>|### \1|g' | \
                perl -pe 's|<h4>(.*?)</h4>|#### \1|g' | \
                perl -pe 's|<h5>(.*?)</h5>|##### \1|g' | \
                perl -pe 's|<h6>(.*?)</h6>|###### \1|g' | \
                sed 's/<\/\?i>/_/g' | \
                sed 's/<\/\?strong>/**/g' | \
                sed 's/<\/\?code>//g' | \
                sed 's/<\/\?ul>//g' | \
                sed 's/<\/li>//g' | \
                sed 's/<li>/\n* /g' | \
                perl -pe 's|<sup>.*?</sup>||g' | \
                perl -pe 's|<a href=["'\''](.*?)["'\'']>(.*?)</a>|[\2](\1)|g' | \
                sed 's/Михаил Сергеевич Горбачёв/(Kyrillische Buchstaben werden in der Gesamtausgabe noch nicht unterstützt)/g'
done | cat -s > /tmp/zerm2pdf.md

pandoc /tmp/zerm2pdf.md -t latex -o "$2/$1.pdf"
